### ISSUE TITLE
grpc reservation-service error: Google.Protobuf.InvalidProtocolBufferException: Full type name for Item is Item;

### ISSUE THREAD

**Issue by diegomgarcia** [PacktPublishing/Practical-Microservices-with-Dapr-and-.NET#11]
Hi I've been trying to make the reservation-service work with grpc as you show in your book, but I'm getting the follow error

Google.Protobuf.InvalidProtocolBufferException: Full type name for Item is Item;

I've been struggling with as the book code was relying I think in an old version of dapr and the Extension don't exists anymore, so after figuring out using the sample provided in this repository I'm getting this error. 

I've seen some threads at the dapr GitHub saying that it should be something related to the way its been calling in the client app, that should be referred as grpc, but that goes very different that was showing in the book. 

So any tips on that ?

**Comment by dabedin** [comment]
The code on https://github.com/PacktPublishing/Practical-Microservices-with-Dapr-and-.NET/tree/main/chapter03 now reflects an updated approach to grpc, with protobuf instead of json payload. If you launch the sample.microservice.order-grpc-client and sample.microservice.reservation-grpc, as in launch ps script:
```
# order-service HTTP + reservation-service gRPC
dapr run --app-id "order-service" --app-port "5001" --dapr-grpc-port "50010" --dapr-http-port "5010" -- dotnet run --project ./sample.microservice.order-grpc-client/sample.microservice.order-grpc-client.csproj --urls="http://+:5001"
dapr run --app-id "reservation-service" --app-port "3000" --app-protocol grpc --dapr-http-port "5020" --dapr-grpc-port "50020" -- dotnet run --project ./sample.microservice.reservation-grpc/sample.microservice.reservation-grpc.csproj --urls="http://+:3000"
```
 Does it work for you?

**Comment by diegomgarcia** [comment]
Hi Davide, sorry for the long time, I will test it. 

But do you know if it will be possible still have the feature the way that it was before ? posting in json and receiving in grpc ?

**Comment by dabedin** [comment]
If you look at the last commit before v1 updates (I think it is https://github.com/PacktPublishing/Practical-Microservices-with-Dapr-and-.NET/tree/b6daee6a50cd50ca2b3246219dbf5dea19103938/chapter03) you have the previous scenario and you can start from there to update it with v1.

**Comment by nithikpackt** [comment]
Thank you @dabedin  for the solution.
